### ISSUE TITLE
Onfido payment

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/crowdsale-website#23]
New flow:

1. Ask for country of origin, kick out anyone from US/UK/Japan/Russia...
1. Ask how much ETH the user wants to contribute.
1. Check if account is certified create a presigned tx for the sale, send it.
1. If not certified, create two presigned txs - one to pay for certification, one for the sale (nonce+1). Send the first one, wait for logs on receiving account before starting the onfido process.

**Comment by ngotchac** [comment]
Outdated
