### ISSUE TITLE
Split out the certification only (no sale) website.

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/crowdsale-website#24]
Use the same backend, ideally gut out existing FE but include prepaying for onfido:

* Allow accounts to be created or loaded, checked if they are certified. If they are, the end.
* Check if the account is funded, if it's not require at least `X` ETH + tx fee to be on the account, wait till it's funded.
* If they aren't, create a presigned tx for `X` ETH to send to the the trusted account that makes requests to the certifier.
* Wait for the tx to be confirmed, then begin onfido, proceed with certification on the backend.

`X` - fixed amount, $5 equivalent.

**Comment by ngotchac** [comment]
Pretty much done!
