### ISSUE TITLE
[UI] Implement the "create a Wallet" journey

### ISSUE THREAD

**Issue by ngotchac** [paritytech/crowdsale-website#6]
When a use clicks on _I don't have a wallet_, the UI should create a wallet with the given information from the User (password) (see the 3 steps on pages 2-4 of the Wireframes)

**Comment by maciejhirsz** [comment]
Can use the [WASM module](https://github.com/paritytech/parity/tree/master/js/src/api/local/ethkey) from the public node for this. I can pick it up, should ideally put [the wasm source](https://github.com/paritytech/parity/tree/master/js/wasm/ethkey) in it's own repo as well.

**Comment by ngotchac** [comment]
(just be sure that there is a JS-only implementation too ; I think this won't be for power users so they might not have the most up-to-date browser)
